name: natogest
description: "Software profesional de gestión ganadera AgTech"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Gestión de Estado y Backend
  flutter_riverpod: ^2.4.9
  supabase_flutter: ^2.0.2
  
  # Persistencia Offline e Identificación
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  
  # UI, Animaciones y Estética
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  
  # Utilidades AgTech (OCR y Cámara)
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Reportes y Exportación (Nivel Pro)
  syncfusion_flutter_xlsio: ^24.1.41
  open_file: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Generadores de código para Hive
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Si tienes activos (logos, imágenes), descomenta y agrégalos aquí:
  # assets:
  #   - assets/images/